# Generated by Django 3.1.7 on 2021-03-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobHunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('date_applied', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>')),
                ('applied_on', models.CharField(choices=[('Indeed', 'Indeed'), ('LinkedIn', 'LinkedIn'), ('Company_website', 'Company website')], default='Company_website', max_length=20)),
                ('reject_email', models.BooleanField(default=False)),
                ('interview', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
